---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-admin
  namespace: adgangskomponent
spec:
  encryptedData:
    password: AgCXFiBcJdFpAqFNO9HS5Q3F9vAptnk5RS3d8NkP/1QPqXd7615c1GP9Cmz8inOLjMEAXBBNPO+hTVBjPe9kV4zwFI/8xBtlg9MrbUEv3JT8TY9kONS3t5jKqWJorEPMO1QT9vkJevUzu8Gkn0BCLXTwHoS1BgakXazoFjYaTh/LKN5LLPYc/xLQrO6zOjtGryLtz1p7r1vtn1BIMEW4jRh/SprB2zxv6dpgaZ5SH1RjmOG8KLi6WSdTI0kCLa2miDJg+ks79DxjVcF4SfLYFu7LMMpNG73x03lboszy5pPUUXhwjjI+/YjzySAa44Dpx9BBLJB+6ULENdFEr/FwMJlTGDTHoIMIwmBw4+sCNvplX/J1hzLF8l7Ji9IWFmc9LttXwLPGb9s5rGTlENpFivOyRbs9jnZcGbKzkdThg4Lr8oH+fghHpB7Z3Tdbx8uSvIR625ES++qIQ+Z+15LXVvzNH/FIvY9tijv0dS6IpquP+jg6CCYUXEGu/WMRR4qLwTHWlKx+7SPe13OUmADQa/EteKa7NtpBJPx36hI8btuaDopljNqpMj1oDVbcbhSQAcaH32mXtS5UD3FCteVvnja00MgOkY4lQsPM7YkhTWvczibWsOP4L92jTe+KvZSnWOi3MJt8ohjmzolb6wYIVs/GNu/xfSpgfYD1XBRksj2lDA90ulMTJG+WH2fDMFASdTWfGLFFKREQIDQ5ISAEkfkBXmmYlZw+D1qDYRQQSvCwkCpHs3akcsrPe9i/U+r7BgSZRWNaidN+ZkGTYjxacXep
    username: AgBxZjVXI6dz9kNkwciY+tzxDJUXdAlQT43NnnKiairTni4SyKvxz/NeyRjvUJDxKQlav0e9cF1UujBzRFN17hYRYcStOf7Hlzt8yoOEvVRxA/axL/zDf4Y8nEh0wwQE63BCgmhe7xQooKVqDWCI1w8pn2IKvLxskAqrPa+Gp+4PVUFVbDTnXcubTJ1MoYCoNP8oB2s9sHwdlZKTWIBr+c9pCqEnm3uHfWf8x9Atq7Jf+p2kPT0biLw3oXlfKk4I15mU7sa2Q0CJjL8B8+OEnIo2/uolQ1/fXqB6TTbZakgjJY4mFHCkZkhPkStHR6jqCBtEWePoLPcEBmRUz12uR4AsX4N6A+lFFkLSl2pnwrbcwUYzjcQ2CxzeTANpXZatkZU07OzQFBCJA4Vgj9gFcRkYXs2mH+v6vlMW9RCHHn+vQdg+hjp0gZZ0BNkudttDUIeTJj8Uv6uWiuooOYhQQ8A3ztB9wYv0apgSBzFY2XGgmDAlgQ4S174yVoTOa6xpk5ZtPp3BzxLOMjOc2Ba4Qg0Ssgz4BXR7oCEF9xi8L1T/XqonjxeZlAKoZ2wvJDaMoXc4vXEoNY3N55XhR94d5Y+oRXLS1v777/OXlgLif6NRxo+rJ8OiVfzwhhPGDq/HYRYwvq8WO9Kf41Uvj0ex0LO4hVWSv86nCvLMlNqpA/wRIlMglN0ltaRoKD5tfH74VrIJlJuezw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-admin
      namespace: adgangskomponent
    type: Opaque
