apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pvc-storage-alerts
  namespace: monitoring
  labels:
    role: alert-rules
spec:
  groups:
  - name: pvc-storage
    rules:

    - alert: KubernetesVolumeFullSoon
      expr: (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) * 100 > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PVC {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is running out of space"
        description: "PVC usage is at {{ printf \"%.2f\" $value }}%."

    - alert: KubernetesVolumeFillingUp
      expr: predict_linear(kubelet_volume_stats_available_bytes[1h], 4 * 3600) < 0
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "PVC {{ $labels.persistentvolumeclaim }} is predicted to run out of space in 4 hours"
