---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgD1YcXtYL2BfOYdku2/ZqgoYCOoEV8slDcpOAyO9gVN8QtoPiNvHY8OjhI88U3w5ikCiQmTvO4GNaCTEKBIKaQiuyP6PYJZzBMCuJqNenCMZcgEyz1R8QIGt0EUeUhko0Uu5NqgUDHnsCfbmOs/g6KQCrB9lbMzsc1GpspTs0W/43xGCOsUn7TQ72SXHRioVa5elxYYnkcsThr/WoFcBeFQk/Hypzo0+AMtk3/pRRlDZTWNvN8UzurnDPZT9tsTCpfyyHbsBqdpWK2r8Wx7d2tCy6pkTBPuRbosoNgymEZEBvV3/XaetK2Tuqnn99m4K/pzJXtTupUv6Hoc4UkhPqpedCz4fSUH+d+y/IvV6/LyhIckadI3n3i6xPHUDGCoGqeecjY5LtINLQhN8YEKLGMYxcRoTFFpeWQ4hKcPAlwWsxdaWXu6x2HmmWAExz1HfeAd+a8D2EXm3NMKK0wzCtlhqPVMsJy2h3/8A7da5Q07iv2Ty/2CeCrHW4diS7gGrzABCsNlLM2CJR+SwtJk6OA2Zb0uolnt0KQ0QoZiqtmX++7/YupLYdRf0C38Sw/Bo5aLKqgoaX+IwMQCOuT+AnS96arWm0TUpQdoFDIb9L0oGU3b65qZKLyMEfB44cT7kBz5YyBg2QcKt3RT+BkADu+k81mdo5KEgagyw82ej04GmouMO2mjLR4h3igbPcw+tVrSk4KKUouHePG7W1QPSHRHBd1Mn9eQ5o1Dib0jE6nptHnmY7RtgaPeWn6iBveGkylTwEpOwgPlb805aTJkwRWE+Y7DCt0EVISWKdm99JAP
  template:
    metadata:
      name: alertmanager-slack
      namespace: monitoring
