---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgBml1wY6jXzKWBSjqyq5dmwjFfCGiAkc7IBXY1VhwNcjt5ZPPkqkJCNg8iADz8l8y4/qSmaeHCFkliv4iEjT+rR9BSUm5y0FgX2Sqfq4JFKHPiNGrMb+hl82GDkRnjp8axbPz/e2ARREhT1YuOZ93wKzR81yJjFo2o5r/Xw0K6MqGPPsLwx+2TpG26LY4mrjdJ+Mhe2wq90fmYLVAR8M38LEgkH5QIrLP0ilXx5At2of6MWrlgk2dttnt86+J9TeAVmsK1IEEiYfskF2WdWA6D2NU8JfK00aIXhihxL3S0KsGPaYCFF35EP+nT3PeQMVRtZgOiSR6e9e8lsTqkOc7Vw9j3vAfueLnm53MTr8CZZAISABkwifc5X/qIReEFzV+9DX2dBvJfAHALR/PUBcGxC+N6UT80jrum53T8WHZx0tmLqQ0zxZGpq/uqFmmxRKDL9+5eBL5oRwKRL1rMgLS2ol6MzJu8KFhManEL2xRPXppusc9LLVx+wMjl+RxdjWpJUhyXMJ44j+h3OkTcZ9NnZJOstuVBlFSMopv2WmuXhLwk6WvH9q/mRiDAzMklCAno59bRN+yVFKyzgoHAil/wOyYqNWkzc7Zhppwm7fTItbM4qKUv8+869cehshgCF5vWP9HA0Kzt0obfkytDgOJLB62+Ir0iR8NDXhWW4DqrXpjLNEHlEhj/gmbHpcIsrcF5H3t/Pdu2CAs1MvOKA4nt9FrdCV31Xv9NsQrSxD+NJZacqAfKwSpTdtYUyhV65ZCs+qY55dmOc9DJQoN2Z9+lu1jkY5PBjT1ZxNgP4wI7W
  template:
    metadata:
      name: slack-webhook
      namespace: monitoring
