---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgCRCicg6QcFKS89PpBeokK09sI3YGVB9SrIHA0rvkVJGk+AVlRwPmPrOwdWftvczVGyGPtVtPF177Ehfm0bbs7Cj2fjdlG5w5Df3ZYqGhdcQJBO8tW3CrhZBxjPqw2hh5Oz5lLCYWPtJlMILAh91G+sn/892tz4ChB7UW4A3QLLeeOBWeMxGPrF55DAljWcw6F0YAsIbIFil8a7k7FEz9YQl56gHVTsBHUJkYZ6OW7kceGuEHNlnuS3uloUWTcnsPWVuSco9Al6RKbrpB4wuYNVFbke5gA5EEVnabvWAzgOsF9oowhpFMA7kKbVISNk1N7+EqgC5amzC/5qtFL4+Bl5/guvs7Ae4lEgNezn4a9dRtIAzaUXRsahXaZIeGu6BiYgyqt3f5OJ/GVQfRdcWjpeskygV17EnmNbnLf+h0okVcWPdzdeANbIAZeKmMIb92Pm8L99SxLPApmG8zF8as2viE+ev20zm5dlEy7NmY5BB4XODz6O7f978zx7apvz8UyIQmRYyUzvwj6apngWvn3ACH7bI1cDNwSCHSOp8g27Y/YsR2EvLssIjbXWMGmMLdJ24/cazdf4iQ/taJaOmUMQm5oDAhg/hgabuqaOuCJ9G7+m37/0RkVEuj2/jOvDcV9eWA1GMnI4F+XMWEBxq3exe1t/ryXcqXdYFYQW3JQu7ZkoTRbM8Fkv0YK51WuTUTgFHyi866SVzGrRUAnz58yY/8EuCDoTGgzNQO5pqGY182cYTm6J+vPQP389MLvk425Q9Z4Q02/fZkiCuVhiRamUgwlusOnm/5UkzuvOc35l
  template:
    metadata:
      name: slack-webhook
      namespace: monitoring
